name: Main

on: push

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: game-ci/unity-test-runner@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
#          projectPath: ./
          projectPath: CoreService.Client.Services.Unity
          unityVersion: 2022.3.7f1
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          