name: Main

on: push

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: game-ci/unity-test-runner@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: ./da-game
          githubToken: ${{ secrets.GITHUB_TOKEN }}